telegram_token: ""
openai_api_key: ""
openai_api_key2: ""
bot_chatgpt: "Майдари"
bot_dalle: "image"
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)